/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;
import java.sql.Connection;
import service.dbconnection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author shibin
 */
public class AD2 extends javax.swing.JFrame {

    /**
     * Creates new form AD2
     */
    public AD2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        busid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hh = new javax.swing.JTextField();
        as = new javax.swing.JComboBox();
        mm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dmm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ds = new javax.swing.JComboBox();
        dhh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        seats = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        type = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(520, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(520, 510));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel2.setText("Bus ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(113, 176, 45, 19);
        jPanel1.add(busid);
        busid.setBounds(194, 177, 157, 22);

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel3.setText("From");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(113, 205, 36, 19);
        jPanel1.add(from);
        from.setBounds(194, 208, 157, 22);
        jPanel1.add(to);
        to.setBounds(194, 235, 157, 22);

        jLabel4.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(113, 234, 35, 19);

        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel5.setText("Arrival");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(113, 267, 46, 22);
        jPanel1.add(hh);
        hh.setBounds(175, 263, 43, 31);

        as.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--", "am", "pm" }));
        jPanel1.add(as);
        as.setBounds(357, 269, 80, 22);

        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        jPanel1.add(mm);
        mm.setBounds(270, 263, 43, 32);

        jLabel6.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel6.setText("Hours");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(222, 268, 44, 19);

        jLabel7.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel7.setText("mins");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(317, 268, 33, 19);
        jPanel1.add(dmm);
        dmm.setBounds(286, 313, 44, 33);

        jLabel11.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel11.setText("mins");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(334, 318, 33, 19);

        ds.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--select--", "am", "pm" }));
        jPanel1.add(ds);
        ds.setBounds(374, 319, 80, 22);
        jPanel1.add(dhh);
        dhh.setBounds(189, 314, 44, 31);

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("Hours");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(237, 318, 42, 19);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel8.setText("Departure");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(113, 318, 71, 19);

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setText("Type");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(113, 364, 33, 19);
        jPanel1.add(fare);
        fare.setBounds(189, 399, 140, 22);

        jLabel12.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel12.setText("Fare");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(113, 398, 32, 19);

        jLabel14.setFont(new java.awt.Font("Traditional Arabic", 1, 16)); // NOI18N
        jLabel14.setText("Seats");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(113, 433, 40, 20);
        jPanel1.add(seats);
        seats.setBounds(189, 430, 73, 22);

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 440, 70, 25);

        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select", "A/C", "Non A/C" }));
        jPanel1.add(type);
        type.setBounds(301, 365, 74, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 170);

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(30, 470, 70, 23);

        jLabel13.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel13.setText("Bus Booking 2020");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 480, 94, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undr.jpg"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 480, 520, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbconnection db=new dbconnection();
        Connection con=db.getconnection();

        String a=hh.getText()+"."+mm.getText()+" "+as.getSelectedItem().toString();
        String b=dhh.getText()+"."+dmm.getText()+" "+ds.getSelectedItem().toString();
        String c=type.getSelectedItem().toString();

        try
        {
            PreparedStatement pst=con.prepareStatement("insert into busdetail values(?,?,?,?,?,?,?,?)");
            pst.setString(1, busid.getText());
            pst.setString(2, from.getText());
            pst.setString(3, to.getText());
            pst.setString(4, a);
            pst.setString(5, b);
            pst.setInt(6, Integer.parseInt(fare.getText()));
            pst.setString(7, c);
            pst.setInt(8, Integer.parseInt(seats.getText()));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Added A New Bus");
            dispose();
            AD1 ad=new AD1();
            ad.setVisible(true);
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
       new AD1().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AD2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AD2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox as;
    private javax.swing.JTextField busid;
    private javax.swing.JTextField dhh;
    private javax.swing.JTextField dmm;
    private javax.swing.JComboBox ds;
    private javax.swing.JTextField fare;
    private javax.swing.JTextField from;
    private javax.swing.JTextField hh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mm;
    private javax.swing.JTextField seats;
    private javax.swing.JTextField to;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
