/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;
import java.sql.*;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.booking;
import model.busdetails;
import service.dbconnection;
import model.user;
/**
 *
 * @author shibin
 */
public class frth extends javax.swing.JFrame {
int trID=10001,no;
    java.sql.Date a;
        java.util.Date s;
        Integer flag;
        PreparedStatement stmt=null;
        ResultSet rs=null;
         Connection con=null;
    /**
     * Creates new form frth
     */
    public frth(Integer n) {
        initComponents();
        no=n;
         dbconnection db=new dbconnection();
     con=db.getconnection();
     display();
    // dbconnection db=new dbconnection();
    // con=db.getconnection();
     
     String sql="select * from booking";
        try {
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            trID=Integer.parseInt(rs.getString("bookid"));
            }
            transid.setText(String.valueOf(trID+1));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
 public void display()
    {
        int i;
        try
        {
        booking book=new booking();
        id.setText(book.getBusid());
        from.setText(book.getFrom());
        to.setText(book.getTo());
        }
        catch(Exception e)
        {
            
        }
    }
    
 public ArrayList<busdetails> getbusdetails()
  {
      ArrayList<busdetails> busdetailsList=new ArrayList<busdetails>();
      dbconnection db=new dbconnection();
      Connection con=db.getconnection();
      Statement st;
      ResultSet rs;
      try
      {
          st=con.createStatement();
          rs=st.executeQuery("select * from busdetail where place_from='"+from.getText()+"' and place_to='"+to.getText()+"'");
          busdetails bus;
          while(rs.next())
          {
            bus=new busdetails();
            bus.setBusid(rs.getInt("busid"));
            bus.setFrom(rs.getString("place_from"));
            bus.setTo(rs.getString("place_to"));
            bus.setArrival(rs.getString("arrival"));
            bus.setDeparture(rs.getString("departure"));
            bus.setFare(rs.getInt("fare"));
            bus.setType(rs.getString("type"));
            bus.setSeat(rs.getInt("seats"));
            busdetailsList.add(bus);
          }
          con.close();
      }
      catch(Exception e)
      {
          System.err.println(e);
      }
      return busdetailsList;
  }
 public int check()
    {
        Integer busid=Integer.parseInt(id.getText()),seatno=0;
        s=date1.getDate();
       a=new java.sql.Date(s.getTime());
       try{
       stmt=con.prepareStatement("select sum(seats) from booking where busid=? and date=?");
       stmt.setInt(1, busid);
       stmt.setDate(2, a);
       rs=stmt.executeQuery();
       if(rs.next())
       {
         seatno=rs.getInt("sum(seats)");
       }
       if(seatno<50)
       {
        flag=1;   
       }
       else
       {
           flag=0;
       }
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, e);
       }
       return flag;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        from = new javax.swing.JTextField();
        transid = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(0, 565));
        setPreferredSize(new java.awt.Dimension(530, 510));

        jPanel1.setPreferredSize(new java.awt.Dimension(530, 510));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel3.setText("From");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 210, 40, 30);

        from.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 0)));
        jPanel1.add(from);
        from.setBounds(180, 210, 150, 30);

        transid.setEditable(false);
        transid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        transid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transidActionPerformed(evt);
            }
        });
        jPanel1.add(transid);
        transid.setBounds(390, 166, 100, 18);

        to.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        jPanel1.add(to);
        to.setBounds(180, 260, 150, 30);

        jLabel9.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel9.setText("Transaction ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 160, 150, 30);

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 270, 34, 14);

        jLabel5.setFont(new java.awt.Font("Sylfaen", 1, 17)); // NOI18N
        jLabel5.setText("Bus ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 310, 60, 40);

        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(id);
        id.setBounds(180, 310, 140, 30);

        quantity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(quantity);
        quantity.setBounds(180, 360, 140, 30);

        jLabel6.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        jLabel6.setText("Quantity");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 370, 66, 22);

        jLabel7.setFont(new java.awt.Font("Sylfaen", 1, 17)); // NOI18N
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 410, 38, 24);

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setText("PROCEED");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 440, 70, 30);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 480, 59, 23);
        jPanel1.add(date1);
        date1.setBounds(180, 410, 154, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Bus Booking 2020");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(400, 495, 112, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undr.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 495, 520, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 160);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 160, 520, 340);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dbconnection db=new dbconnection();
        Connection con=db.getconnection();
        booking book=new booking();
        s=date1.getDate();
        a=new java.sql.Date(s.getTime());
        check();
        int temp=0,fa=0;
        if(flag==1)
        {
            try
            {
                Statement st=con.createStatement();
                ResultSet res=st.executeQuery("select seats,fare from busdetail where busid='"+id.getText()+"'");
                while(res.next())
                {
                    fa=res.getInt("fare");
                    temp=res.getInt("seats");
                }

                if(temp>=Integer.parseInt(quantity.getText()))
                {
                    PreparedStatement pst=con.prepareStatement("insert into booking(bookid,busid,place_from,place_to,date,seats,amount) values(?,?,?,?,?,?,?)");
                    pst.setString(1, transid.getText());
                    pst.setString(2, id.getText());
                    pst.setString(3, from.getText());
                    pst.setString(4, to.getText());
                    pst.setDate(5, a);
                    pst.setInt(6, Integer.parseInt(quantity.getText()));
                    pst.setInt(7, fa*Integer.parseInt(quantity.getText()));
                    pst.executeUpdate();
                    dispose();
                    passdit sv=new passdit(0,Integer.parseInt(id.getText()),no);
                    sv.setVisible(true);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Enter Valid Seats");
                }
            }
            catch(Exception e)
            {
                System.err.println(e);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Over");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(no==1)
        {
            dispose();
            new AD1().setVisible(true);
        }
        else
        {
           dispose();
            new thrd().setVisible(true); 
        }

    }//GEN-LAST:event_jButton2ActionPerformed
private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
  
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField from;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField to;
    private javax.swing.JTextField transid;
    // End of variables declaration//GEN-END:variables
}
