/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;
import java.sql.*;
import java.util.ArrayList;
import javax.persistence.Table;
import javax.swing.JOptionPane;
import model.busdetails;
import service.dbconnection;
import javax.swing.table.DefaultTableModel;
import model.user;
import javax.swing.table.DefaultTableModel;
import model.booking;
/**
 *
 * @author shibin
 */
public class nine extends javax.swing.JFrame {
Date dt;
    Connection con=null;
    PreparedStatement stmt=null;
    ResultSet rs=null;
    /**
     * Creates new form nine
     */
    public nine(Date a) {
        initComponents();
    dbconnection db=new dbconnection();
        con=db.getconnection();
        dt=a;
    try{
        
    stmt=con.prepareStatement("select *from busdetail");
    rs=stmt.executeQuery();
    
    rs.first();
    do{
    Integer id=rs.getInt("busid"),seat=0,st;
    stmt=con.prepareStatement("select sum(seats) from booking where busid=? and date=?");
    stmt.setInt(1, id);
    stmt.setDate(2,dt);
    
    ResultSet rs2=stmt.executeQuery();
    if(rs2.next())
    {
     seat=rs2.getInt("sum(seats)");
    }
    st=50-seat;
    Object[] row=new Object[]{id,rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),st};
    DefaultTableModel model=(DefaultTableModel) Table.getModel();
    model.addRow(row);
    }while(rs.next());
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
    }
    }
 public ArrayList<busdetails> getbusdetails()
  {
      ArrayList<busdetails> busdetailsList=new ArrayList<busdetails>();
      dbconnection db=new dbconnection();
      Connection con=db.getconnection();
      Statement st;
      ResultSet rs;
      try
      {
          st=con.createStatement();
          rs=st.executeQuery("select * from busdetail");
          busdetails bus;
          while(rs.next())
          {
            bus=new busdetails();
            bus.setBusid(rs.getInt("busid"));
            bus.setFrom(rs.getString("place_from"));
            bus.setTo(rs.getString("place_to"));
            bus.setArrival(rs.getString("arrival"));
            bus.setDeparture(rs.getString("departure"));
            bus.setFare(rs.getInt("fare"));
            bus.setType(rs.getString("type"));
            bus.setSeat(rs.getInt("seats"));
            busdetailsList.add(bus);
          }
          con.close();
      }
      catch(Exception e)
      {
          System.err.println(e);
      }
      return busdetailsList;
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(520, 520));
        jPanel1.setLayout(null);

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bus ID", "From", "To", "Arrival", "Departure", "Fare", "Type", "Seats"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 196, 520, 266);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Bus Booking 2020");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 495, 112, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 190);

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 480, 61, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undr.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 490, 520, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        booking book=new booking();
        dbconnection db=new dbconnection();
        Connection con=db.getconnection();
        String s=Table.getValueAt(Table.getSelectedRow(),0).toString();
        System.out.println(s);
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from busdetail where busid='"+s+"'");
            if(rs.next()){
                book.setBusid(rs.getString("busid"));
                book.setFrom(rs.getString("place_from"));
                book.setTo(rs.getString("place_to"));
            }
            dispose();
            frth fr=new frth(0);
            fr.setVisible(true);
        }
        catch(Exception ex){
            System.out.println("err"+ex);
        }
    }//GEN-LAST:event_TableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        user us=new user();
        dispose();
        if(us.getId()==0)
        {
            thrd th=new thrd();
            th.setVisible(true);
        }
        else if(us.getId()==1)
        {
            AD1 ad=new AD1();
            ad.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new nine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
