/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bus;
import static java.awt.PageAttributes.MediaType.C;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.booking;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import service.dbconnection;
/**
 *
 * @author shibin
 */
public class SVN extends javax.swing.JFrame {
Integer trans_id,i=1,no;
    public SVN(int tid,Integer n) {
        initComponents();
        no=n;
        trans_id=tid;
        
        bookget();
         dbconnection db=new dbconnection();
        Connection con=db.getconnection();
        String fr=null,to=null;
        try {
            String sql="select * from busdetail where busid=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, busid.getText());
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
                fr=rs.getString("place_from");
                to=rs.getString("place_to");
                
            }
            jTextField1.setText(fr);
            jTextField2.setText(to);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    /**
     * Creates new form SVN
     */
    public SVN() {
        initComponents();
    }
public void bookget()
{
    dbconnection db=new dbconnection();
    Connection con=db.getconnection();
    
    try
    {
         Statement st1=con.createStatement();
        ResultSet res=st1.executeQuery("select bookid,busid,seats,amount from booking where bookid=(select max(bookid) from booking)");
        while(res.next())
        {
            bid.setText(res.getString("bookid"));
            busid.setText(res.getString("busid"));
            total.setText(res.getString("amount"));   
        }
        PreparedStatement st=con.prepareStatement("select * from passdt where Trans_id=?");
        st.setInt(1, trans_id);
       // JOptionPane.showMessageDialog(null, st);
       ResultSet rs=st.executeQuery();
        while(rs.next())
        {
            
         Object[] row=new Object[]{rs.getString("name"),rs.getString("age"),rs.getString("gender"),rs.getString("mobile"),rs.getString("aadhar")};
         DefaultTableModel model=(DefaultTableModel) pass.getModel();
         model.addRow(row);
        }
        bid.setEditable(false);
        busid.setEditable(false);
        total.setEditable(false);
        get();
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
}

public void get()
{
     dbconnection db=new dbconnection();
    Connection conn=db.getconnection();
     booking book=new booking();
     int fa=0,tot=0;
    try
    {
         Statement st=conn.createStatement();
        ResultSet rs=st.executeQuery("select * from busdetail where busid='"+busid.getText()+"'");
        while(rs.next())
        {
            fare.setText(rs.getString("fare"));
            type.setText(rs.getString("type"));
                    }
       
        fare.setEditable(false);
        type.setEditable(false);
        
       
       
    }
    catch(Exception e)
    {
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        busid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pass = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(520, 650));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("To");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 200, 34, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("FROM");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(60, 200, 50, 20);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 200, 120, 20);

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(330, 200, 150, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Transaction ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 240, 116, 22);

        bid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(bid);
        bid.setBounds(250, 240, 170, 20);

        busid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        busid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busidActionPerformed(evt);
            }
        });
        jPanel1.add(busid);
        busid.setBounds(250, 280, 170, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Bus ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 280, 54, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Fare");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 320, 33, 22);

        fare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareActionPerformed(evt);
            }
        });
        jPanel1.add(fare);
        fare.setBounds(250, 320, 170, 20);

        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(total);
        total.setBounds(250, 360, 170, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(170, 360, 40, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Type");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 400, 39, 22);

        type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(type);
        type.setBounds(250, 400, 170, 20);

        pass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Gender", "Mobile no:", "Aadhar no:"
            }
        ));
        jScrollPane1.setViewportView(pass);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 440, 500, 140);

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 610, 59, 23);

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton1.setText("BOOK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 590, 69, 21);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("PRINT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(430, 590, 67, 23);

        jLabel14.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel14.setText("Bus Booking 2020");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(410, 620, 100, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/undr.jpg"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 618, 520, 31);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frame3.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 190, 520, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void busidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busidActionPerformed

    private void fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        frth fr=new frth(no);
        fr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dbconnection db=new dbconnection();
        Connection con=db.getconnection();
        try
        {
            PreparedStatement st=con.prepareStatement("update booking set busid=?,amount=? where bookid=?");
            st.setString(1, busid.getText());
            st.setString(2, total.getText());
            st.setString(3, bid.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Booked");
            dispose();
            thrd fr=new thrd();
            fr.setVisible(true);

            i++;
        }
        catch(Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Map<String,Object> param=new HashMap<>();
            param.put("TransID",Integer.parseInt(bid.getText()));
            param.put("busid",Integer.parseInt(busid.getText()));
            param.put("fare",Integer.parseInt(fare.getText()));
            param.put("total",Integer.parseInt(total.getText()));
            param.put("type",type.getText());
            param.put("to",jTextField2.getText());
            param.put("from",jTextField1.getText());
            DefaultTableModel m=(DefaultTableModel) pass.getModel();
            JRTableModelDataSource datasource=new JRTableModelDataSource(m);
            JasperDesign jd=JRXmlLoader.load("report\\booking.jrxml");
            JasperReport jp=JasperCompileManager.compileReport(jd);
            JasperPrint jprint=JasperFillManager.fillReport(jp, param,datasource);
            JasperViewer.viewReport(jprint);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
       
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SVN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField busid;
    private javax.swing.JTextField fare;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable pass;
    private javax.swing.JTextField total;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
